#!/usr/bin/env python3
"""Regenerate Sources/PDC002Kit/Protocol/SBox.swift.

Derives the .pd1s substitution table from a known plaintext/ciphertext pair:
  reference/PDC002/firmware/polling-non-flash.raw   (decoded body, text format)
  reference/PDC002_software/PDC002固件_230713/PDC002_2.0轮询不闪烁.pd1s

The .pd1s body starts at offset 48 (after the encoded gzutapp header) and is
byte-for-byte the raw firmware passed through the table. The pair covers all
256 byte values, so the full bijection is recoverable.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RAW = os.path.join(ROOT, "reference/PDC002/firmware/polling-non-flash.raw")
PD1S = os.path.join(
    ROOT, "reference/PDC002_software/PDC002固件_230713/PDC002_2.0轮询不闪烁.pd1s"
)
OUT = os.path.join(ROOT, "Sources/PDC002Kit/Protocol/SBox.swift")
BODY_OFFSET = 48


def main():
    raw = []
    with open(RAW) as f:
        for line in f:
            raw.extend(int(x) for x in line.split())
    encoded = open(PD1S, "rb").read()
    assert len(encoded) == len(raw) + BODY_OFFSET, "reference pair size mismatch"

    sbox = [None] * 256  # plain -> encoded
    for plain, enc in zip(raw, encoded[BODY_OFFSET:]):
        if sbox[plain] is not None and sbox[plain] != enc:
            sys.exit(f"conflict at plain byte {plain}")
        sbox[plain] = enc
    if None in sbox:
        sys.exit(f"incomplete table: {sbox.count(None)} values unseen")
    if len(set(sbox)) != 256:
        sys.exit("table is not a bijection")

    inv = [None] * 256
    for plain, enc in enumerate(sbox):
        inv[enc] = plain

    def swift_array(name, values):
        lines = [f"public let {name}: [UInt8] = ["]
        for i in range(0, 256, 16):
            row = ", ".join(f"0x{v:02X}" for v in values[i : i + 16])
            lines.append(f"    {row},")
        lines.append("]")
        return "\n".join(lines)

    with open(OUT, "w") as f:
        f.write(
            "// Generated by Scripts/gen_sbox.py — do not edit by hand.\n"
            "// Substitution table for the WITRN .pd1s firmware container.\n"
            "// sbox maps decoded (raw firmware) bytes to encoded file bytes;\n"
            "// sboxInverse is the reverse mapping used to decode .pd1s files.\n\n"
        )
        f.write(swift_array("sbox", sbox))
        f.write("\n\n")
        f.write(swift_array("sboxInverse", inv))
        f.write("\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
